language: php

sudo: false

dist: trusty

matrix:
  include:
  - php: '7.1'
  - php: hhvm
  - php: nightly
  fast_finish: true

before_script:
# php deps
- composer self-update
- composer install --dev

script:
- echo "skipping tests"